library verilog;
use verilog.vl_types.all;
entity NCO_NEW_nco_ii_0 is
    generic(
        mpr             : integer := 12;
        opr             : integer := 24;
        apr             : integer := 32;
        apri            : integer := 16;
        aprf            : integer := 32;
        aprp            : integer := 16;
        aprid           : integer := 21;
        dpri            : integer := 4;
        rdw             : integer := 12;
        rawc            : integer := 8;
        rnwc            : integer := 256;
        rawf            : integer := 8;
        rnwf            : integer := 256;
        Pn              : integer := 16384;
        mxnbc           : integer := 3072;
        mxnbf           : integer := 3072;
        rsfc            : string  := "NCO_NEW_nco_ii_0_sin_c.hex";
        rsff            : string  := "NCO_NEW_nco_ii_0_sin_f.hex";
        rcfc            : string  := "NCO_NEW_nco_ii_0_cos_c.hex";
        rcff            : string  := "NCO_NEW_nco_ii_0_cos_f.hex";
        nc              : integer := 1;
        log2nc          : integer := 0;
        outselinit      : integer := -1;
        paci0           : integer := 0;
        paci1           : integer := 0;
        paci2           : integer := 0;
        paci3           : integer := 0;
        paci4           : integer := 0;
        paci5           : integer := 0;
        paci6           : integer := 0;
        paci7           : integer := 0;
        hyper_pipeline  : integer := 0
    );
    port(
        clk             : in     vl_logic;
        reset_n         : in     vl_logic;
        clken           : in     vl_logic;
        phi_inc_i       : in     vl_logic_vector;
        fsin_o          : out    vl_logic_vector;
        out_valid       : out    vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of mpr : constant is 1;
    attribute mti_svvh_generic_type of opr : constant is 1;
    attribute mti_svvh_generic_type of apr : constant is 1;
    attribute mti_svvh_generic_type of apri : constant is 1;
    attribute mti_svvh_generic_type of aprf : constant is 1;
    attribute mti_svvh_generic_type of aprp : constant is 1;
    attribute mti_svvh_generic_type of aprid : constant is 1;
    attribute mti_svvh_generic_type of dpri : constant is 1;
    attribute mti_svvh_generic_type of rdw : constant is 1;
    attribute mti_svvh_generic_type of rawc : constant is 1;
    attribute mti_svvh_generic_type of rnwc : constant is 1;
    attribute mti_svvh_generic_type of rawf : constant is 1;
    attribute mti_svvh_generic_type of rnwf : constant is 1;
    attribute mti_svvh_generic_type of Pn : constant is 1;
    attribute mti_svvh_generic_type of mxnbc : constant is 1;
    attribute mti_svvh_generic_type of mxnbf : constant is 1;
    attribute mti_svvh_generic_type of rsfc : constant is 1;
    attribute mti_svvh_generic_type of rsff : constant is 1;
    attribute mti_svvh_generic_type of rcfc : constant is 1;
    attribute mti_svvh_generic_type of rcff : constant is 1;
    attribute mti_svvh_generic_type of nc : constant is 1;
    attribute mti_svvh_generic_type of log2nc : constant is 1;
    attribute mti_svvh_generic_type of outselinit : constant is 1;
    attribute mti_svvh_generic_type of paci0 : constant is 1;
    attribute mti_svvh_generic_type of paci1 : constant is 1;
    attribute mti_svvh_generic_type of paci2 : constant is 1;
    attribute mti_svvh_generic_type of paci3 : constant is 1;
    attribute mti_svvh_generic_type of paci4 : constant is 1;
    attribute mti_svvh_generic_type of paci5 : constant is 1;
    attribute mti_svvh_generic_type of paci6 : constant is 1;
    attribute mti_svvh_generic_type of paci7 : constant is 1;
    attribute mti_svvh_generic_type of hyper_pipeline : constant is 1;
end NCO_NEW_nco_ii_0;
